//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillingInfo
    {
        public System.Guid Id { get; set; }
    
        public virtual PhoneNumber PhoneNumbers { get; set; }
        public virtual Email Emails { get; set; }
        public virtual Address Addresses { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Reservation Reservation { get; set; }
    }
}
