//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomType
    {
        public System.Guid Id { get; set; }
        public int BaseRate { get; set; }
        public int Inventory { get; set; }
        public string Type { get; set; }
        public string Ameneties { get; set; }
        public string Description { get; set; }
    
        public virtual Reservation Reservation { get; set; }
    }
}
