//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomOccupancy
    {
        public System.DateTime Date { get; set; }
        public System.Guid Id { get; set; }
        public int Occupancy { get; set; }
    
        public virtual RoomType RoomType { get; set; }
    }
}
